# Generated by Django 5.2.1 on 2025-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_alter_servicerecord_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plot_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
