# Generated by Django 5.2.1 on 2025-06-19 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
