# Generated by Django 5.2.1 on 2025-06-19 06:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_alter_expense_expense_date_alter_invoice_date_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('loan_reason', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateField(default=datetime.date.today)),
                ('loan_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
